window.HARD_CODED_NEWS = [
  {id:1,category:'SIGHTING',source:'HBC北海道放送',date:'2026-09-10',region:'北海道標茶町',title:'道路中央を走るクマをドライバーが目撃　北海道標茶町',summary:'国道272号で体長約1メートルのクマが確認されました。',content:'9月10日朝、北海道標茶町の国道272号で、走行中のトラックの前を体長約1メートルのクマが走る様子が目撃されました。クマはしばらく道路上を移動した後、道路脇の森へ入ったとされています。周辺を通行する際は、早朝・夕方を中心に速度を落とし、クマを見かけても近づかないよう注意が必要です。',images:['https://newsdig.ismcdn.jp/mwimgs/c/2/680mw/img_c23ae0654e2944c96d7acf735fe8135563579.jpg'],sourceUrl:'https://newsdig.tbs.co.jp/articles/hbc/2934118'},
  {id:2,category:'SIGHTING',source:'関西テレビ',date:'2026-09-07',region:'京都府舞鶴市',title:'京都・舞鶴市で緊急銃猟　住宅付近に出没したツキノワグマ',summary:'住宅の軒下で親子とみられるクマが確認され、京都府で初の緊急銃猟が行われました。',content:'9月3日夕方、京都府舞鶴市で住宅の軒下に親子とみられるツキノワグマ2頭がいるとの通報がありました。市と警察は周辺の安全確保を進め、緊急銃猟を決定しました。捕獲後も子グマの目撃情報があり、周辺では警戒と見回りが続けられました。',images:['https://www.ktv.jp/news/wp-content/uploads/sites/2/2026/09/Still0904_00183.jpg','https://www.ktv.jp/news/wp-content/uploads/sites/2/2026/09/Still0904_00184.jpg','https://www.ktv.jp/news/wp-content/uploads/sites/2/2026/09/Still0904_00193.jpg','https://www.ktv.jp/news/wp-content/uploads/sites/2/2026/09/Still0904_00200.jpg'],sourceUrl:'https://www.ktv.jp/news/feature/260904-kuma/'},
  {id:3,category:'SIGHTING',source:'北海道文化放送',date:'2026-09-09',region:'北海道富良野市',title:'富良野駅構内で子グマ目撃　夜間の普通列車2本を運休',summary:'駅構内付近で子グマが目撃され、夜間作業の安全確保のため列車が運休しました。',content:'9月9日朝、JR富良野駅構内で子グマ1頭が目撃されました。JR北海道は夜間の車両入れ替え作業を安全に行えないと判断し、富良野線の普通列車2本を運休しました。子グマは駅西側へ立ち去ったとされ、駅周辺では注意が呼びかけられました。',images:['https://fnn.ismcdn.jp/mwimgs/3/a/780/img_3ae42d05eecfef377fc9252cf44447ee180422.jpg'],sourceUrl:'https://www.fnn.jp/articles/-/1111370'},
  {id:4,category:'SIGHTING',source:'北海道文化放送',date:'2026-09-06',region:'北海道喜茂別町',title:'ゴルフ場でクマ2頭を目撃　臨時休業と警戒を実施',summary:'利用客が9番ホール付近で成獣とみられるクマ2頭を目撃しました。',content:'北海道喜茂別町のゴルフ場で、利用客が9番ホール付近にクマ2頭がいるのを目撃しました。ゴルフ場は安全のため臨時休業し、警察はパトロールを増やして注意を呼びかけました。現場確認時にはクマや足跡は見つかっていません。',images:['https://fnn.ismcdn.jp/mwimgs/3/a/780/img_3ae42d05eecfef377fc9252cf44447ee180422.jpg'],sourceUrl:'https://www.fnn.jp/articles/-/1108790'},
  {id:5,category:'SIGHTING',source:'福島テレビ',date:'2026-09-07',region:'福島県福島市',title:'福島市でクマ目撃情報　国道4号付近でも確認',summary:'9月5日と6日に福島市内で体長約1メートルのクマが目撃されました。',content:'福島県福島市では、9月5日夜に二子塚字庄司付近、6日夜に平石字蛇石の国道4号付近でクマ1頭の目撃情報がありました。情報は警察署の広報をもとに公表されており、夜間や早朝の単独行動を避け、周辺情報を確認するよう注意が呼びかけられています。',images:['https://fnn.ismcdn.jp/mwimgs/e/d/780/img_ed5b5b1f272adc398cda52817d69ddd972257.jpg'],sourceUrl:'https://www.fnn.jp/articles/-/1109263'},
  {id:6,category:'SIGHTING',source:'長野放送',date:'2026-09-07',region:'長野県伊那市・軽井沢町',title:'キノコ採り中の男性2人がクマに襲われる　長野県',summary:'伊那市と軽井沢町で2日連続して人身被害が発生しました。',content:'長野県では、伊那市と軽井沢町の山林でキノコ採りをしていた男性がクマに襲われる被害が相次ぎました。伊那市では男性が顔や体にけがをし、軽井沢町でも男性が頭や腕にけがをしました。自治体は、早朝・夕方を避け、鈴やラジオで人の存在を知らせるよう呼びかけています。',images:['https://www.nbs-tv.co.jp/news/data/29856/image.jpg'],sourceUrl:'https://www.fnn.jp/articles/-/1109536'},
  {id:7,category:'SIGHTING',source:'さくらんぼテレビ',date:'2026-09-08',region:'山形県天童市',title:'天童市の住宅街でクマ出没　学校周辺も警戒',summary:'住宅街に現れたクマを受け、付近の学校が臨時休校となりました。',content:'山形県天童市では住宅街にクマが出没し、猟友会などが捕獲を試みました。付近の小学校などは安全確保のため臨時休校となり、箱わなが設置されました。クマの所在が確認できない状況が続いたため、地域では警戒が続けられました。',images:['https://img.youtube.com/vi/ssFMGnnhi1M/hqdefault.jpg'],sourceUrl:'https://www.fnn.jp/articles/-/1110499'},
  {id:8,category:'SIGHTING',source:'北海道文化放送',date:'2026-09-05',region:'北海道砂川市',title:'砂川市で5日連続のクマ目撃　交差点付近で確認',summary:'十字路付近でクマ1頭が目撃され、警察がパトロールを強化しました。',content:'北海道砂川市では9月4日、車を運転していた人が十字路交差点付近でクマ1頭を目撃しました。市内では目撃が続いており、住宅街でも確認されていたことから、警察が周辺のパトロールを強化しました。クマを見かけた場合は距離を取り、自治体や警察へ連絡する必要があります。',images:['https://fnn.ismcdn.jp/mwimgs/8/a/780/img_8afc2d15e16dada0f8edf1e41c582e19183940.jpg'],sourceUrl:'https://www.fnn.jp/articles/-/1108423'},
  {id:9,category:'SAFETY',source:'テレビ朝日',date:'2026-09-09',region:'北海道滝上町',title:'秋のクマ活動期を前に　ドローンで農地周辺を調査',summary:'農作物被害が続く地域で、ドローンを使った調査と対策が進められています。',content:'北海道滝上町では、デントコーン畑などでの被害を受け、クマの動きを把握するためドローン調査が行われています。秋はクマが餌を求めて行動範囲を広げる時期で、畑の中へ人が入らずに状況を確認する手段として活用されています。地域では捕獲だけでなく、人里へ近づけないための予防策も進められています。',images:['https://img.youtube.com/vi/1gOo2B6OMjc/hqdefault.jpg'],sourceUrl:'https://news.tv-asahi.co.jp/news_society/articles/000532225.html'},
  {id:10,category:'OFFICIAL',source:'秋田県',date:'2026-09-10',region:'秋田県',title:'秋のクマ事故防止強化期間を開始　秋田県',summary:'9月15日から10月31日まで、県が事故防止対策を呼びかけています。',content:'秋田県は9月15日から10月31日までを秋のクマ事故防止強化期間とし、山地だけでなく生活圏での遭遇にも注意を呼びかけています。果樹や農作物が人里にある時期は、クマが近づく可能性があるため、食べ物や生ごみを屋外へ放置しないこと、目撃情報を確認することが重要です。',images:['https://img.youtube.com/vi/maF71T79th0/hqdefault.jpg'],sourceUrl:'https://www.pref.akita.lg.jp/pages/archive/23295'}
];

window.newsEscape = function (value) { var node = document.createElement('div'); node.textContent = value || ''; return node.innerHTML; };
window.newsImage = function (news) { return news.images[0] || '/resources/img/brand/kumano-mae-splash.png'; };
